### ISSUE TITLE
Crowdsource building a demo sound pack - tell me which sounds to use

### ISSUE THREAD

**Issue by mungewell** [mungewell/uno-drum-utils#6]
I was asked if I could offer a demo, well yes... but I'm not doing all the work ;-)

We can use any samples, but to make it easier I would suggest using the sounds from this 20MByte basic pack.
https://archive.org/details/DrumSamples.orgDS1000archive

I set up a frame work here:
https://github.com/mungewell/uno-drum-utils/tree/main/sound_pack_demo

There are `'before.txt'` and `'DrumSamples-DS1000.txt'` files which detail the sample lengths of each file. Since we are using `'--replace'` the samples the time duration should be same/shorter. Longer samples will be clipped.

Eventually we will build a pack from scratch, but I am being cautious as I don't know the limitations of the UNO Drum yet.

**Comment by mungewell** [comment]
In this example I used the same sample for each of the CowBell samples to be re-packed:
```
# Cowbell
sox DrumSamples.org-DS1000/Cowbells/cowbell1.wav -c 1 -b 16 -e signed unpacked/sample-04-1.wav rate 32000
sox DrumSamples.org-DS1000/Cowbells/cowbell1.wav -c 1 -b 16 -e signed unpacked/sample-04-2.wav rate 32000
sox DrumSamples.org-DS1000/Cowbells/cowbell1.wav -c 1 -b 16 -e signed unpacked/sample-04-3.wav rate 32000
sox DrumSamples.org-DS1000/Cowbells/cowbell1.wav -c 1 -b 16 -e signed unpacked/sample-04-4.wav rate 32000
sox DrumSamples.org-DS1000/Cowbells/cowbell1.wav -c 1 -b 16 -e signed unpacked/sample-04-5.wav rate 32000
```

So, if others scan though 1000 samples to tell me which to use, I will pack them and upload the resultant DFU.

**Comment by mungewell** [comment]
When attempting to figure out how much storage space is available, we can use the '--summarize' function to inspect the various sound packs which IK have published.
```

simon@thevoid:~/uno-drum-utils-github/sound_packs/summary$ grep "Total length" *.txt | grep "bytes"
Uno_Drum_lib_Anthology1.dfu.txt:Total length: 502009 bytes
Uno_Drum_lib_Anthology10.dfu.txt:Total length: 630288 bytes
Uno_Drum_lib_Anthology2.dfu.txt:Total length: 610069 bytes
Uno_Drum_lib_Anthology3.dfu.txt:Total length: 650843 bytes
Uno_Drum_lib_Anthology4.dfu.txt:Total length: 775746 bytes
Uno_Drum_lib_Anthology5.dfu.txt:Total length: 587135 bytes
Uno_Drum_lib_Anthology6.dfu.txt:Total length: 687967 bytes
Uno_Drum_lib_Anthology7.dfu.txt:Total length: 776251 bytes
Uno_Drum_lib_Anthology8.dfu.txt:Total length: 782492 bytes
Uno_Drum_lib_Anthology9.dfu.txt:Total length: 573776 bytes
Uno_Drum_lib_DMX.dfu.txt:Total length: 680608 bytes
Uno_Drum_lib_Factory.dfu.txt:Total length: 603867 bytes
Uno_Drum_lib_STG.dfu.txt:Total length: 554189 bytes
```

Looks like "Anthology8" is the largest pack with 782492 bytes, which equates to 16.301750 sec

**Comment by Improhardwarejam** [comment]
I could check the samples and suggest some. Should it be 5 samples per pad?

**Comment by mungewell** [comment]
The official position is:

- Analog + 4 PCM samples
- Non-Analog + 5 PCM samples

The device can actually handle more or less, it will display a count up-to 9 per pad (although can go higher with a blank value shown) and down to 1. I have not yet tried a pack with zero samples on a pad.

The GUI application assumes the official and does not change to reflect actual count(s) in pack.

**Comment by Improhardwarejam** [comment]
Kick1 = Bassdrum3,distortedkick8,bassdrum9,bassdrum15
Kick2 = bassdrum49,bassrum87,bassdrum90,bassdrum86
Snare = distortedsnare6,snaredrum21,distortedsnare13,distortedsnare63
Closed HH = hihats1,hihats5,hihats15,hihats46
Open HH = hihats47,hihats,63,hihats94,hihats84
Claps = can remain original if possible ? since there are no claps on the zip but maybe could use kettledrum sounds instead 
Tom1 = bongo5,bongo6,bongo7,bongo8,bongo9
Tom2 = conga5, conga6,conga7,conga8,conga9
Rim = rattle3,rattle4,rattle5,tambourine2,tambourine3
Cowbell = cowbell1,cowbell2,cowbell3,cowbell9,cowbell10
Ride = triangle2,triangle3,triangle4,triangle5,triangle10
Cymbal = cymbal1,cymbal9,cymbal2,cymbal5,cymbalcrash7

**Comment by mungewell** [comment]
@Improhardwarejam 

Not a bad selection, but the problem is now that the overall length is too large to fit in the pack. We haven't yet found out how much we can use, and I've limited the building of packs only use lengths '<=' the source pack for safety.

Before:
```
Total length: 603867 bytes
Total length: 12.580375 sec
```
After:
```
Number of samples: 54
Sample 1-1: 6425 (9638 bytes, 0.200781 sec)
Sample 1-2: 4021 (6032 bytes, 0.125656 sec)
Sample 1-3: 4011 (6017 bytes, 0.125344 sec)
Sample 1-4: 8015 (12023 bytes, 0.250469 sec)
Sample 1-5: 8015 (12023 bytes, 0.250469 sec)
Sample 2-1: 13159 (19739 bytes, 0.411219 sec)
Sample 2-2: 13622 (20433 bytes, 0.425687 sec)
Sample 2-3: 12422 (18633 bytes, 0.388188 sec)
Sample 2-4: 9604 (14406 bytes, 0.300125 sec)
Sample 2-5: 6422 (9633 bytes, 0.200687 sec)
Sample 3-1: 541 (812 bytes, 0.016906 sec)
Sample 3-2: 1280 (1920 bytes, 0.040000 sec)
Sample 3-3: 2539 (3809 bytes, 0.079344 sec)
Sample 3-4: 1641 (2462 bytes, 0.051281 sec)
Sample 3-5: 2958 (4437 bytes, 0.092438 sec)
Sample 4-1: 3878 (5817 bytes, 0.121188 sec)
Sample 4-2: 3841 (5762 bytes, 0.120031 sec)
Sample 4-3: 4801 (7202 bytes, 0.150031 sec)
Sample 4-4: 8013 (12020 bytes, 0.250406 sec)
Sample 4-5: 4008 (6012 bytes, 0.125250 sec)
Sample 5-1: 11200 (16800 bytes, 0.350000 sec)
Sample 5-2: 16011 (24017 bytes, 0.500344 sec)
Sample 5-3: 9614 (14421 bytes, 0.300438 sec)
Sample 5-4: 6401 (9602 bytes, 0.200031 sec)
Sample 5-5: 12824 (19236 bytes, 0.400750 sec)
Sample 6-1: 64001 (96002 bytes, 2.000031 sec)
Sample 6-2: 32032 (48048 bytes, 1.001000 sec)
Sample 6-3: 32000 (48000 bytes, 1.000000 sec)
Sample 6-4: 32001 (48002 bytes, 1.000031 sec)
Sample 6-5: 16024 (24036 bytes, 0.500750 sec)
Sample 7-1: 8028 (12042 bytes, 0.250875 sec)
Sample 7-2: 6417 (9626 bytes, 0.200531 sec)
Sample 7-3: 9604 (14406 bytes, 0.300125 sec)
Sample 7-4: 32022 (48033 bytes, 1.000687 sec)
Sample 8-1: 16025 (24038 bytes, 0.500781 sec)
Sample 8-2: 12817 (19226 bytes, 0.400531 sec)
Sample 8-3: 16026 (24039 bytes, 0.500812 sec)
Sample 8-4: 12807 (19211 bytes, 0.400219 sec)
Sample 9-1: 4825 (7238 bytes, 0.150781 sec)
Sample 9-2: 4823 (7235 bytes, 0.150719 sec)
Sample 9-3: 4826 (7239 bytes, 0.150812 sec)
Sample 9-4: 6423 (9635 bytes, 0.200719 sec)
Sample 10-1: 5761 (8642 bytes, 0.180031 sec)
Sample 10-2: 3572 (5358 bytes, 0.111625 sec)
Sample 10-3: 3229 (4844 bytes, 0.100906 sec)
Sample 10-4: 6424 (9636 bytes, 0.200750 sec)
Sample 11-1: 4825 (7238 bytes, 0.150781 sec)
Sample 11-2: 8012 (12018 bytes, 0.250375 sec)
Sample 11-3: 8002 (12003 bytes, 0.250063 sec)
Sample 11-4: 6401 (9602 bytes, 0.200031 sec)
Sample 12-1: 19200 (28800 bytes, 0.600000 sec)
Sample 12-2: 12800 (19200 bytes, 0.400000 sec)
Sample 12-3: 12800 (19200 bytes, 0.400000 sec)
Sample 12-4: 9600 (14400 bytes, 0.300000 sec)
Total length: 879903 bytes
Total length: 18.331031 sec
```

I note that some samples have a lot(?) of empty 'tail' which can be clipped/faded out, with `fade <fade-in> <start-fade-out> <fade-out>` for example:
```
sox DrumSamples.org-DS1000/KettleDrums/kettledrum1.wav $ss unpacked/sample-12-1.wav fade 0 0.6 0.01
```

So the next stage would be to figure out some clipping values, I've attached what I have so far...
[do_it.sh.txt](https://github.com/mungewell/uno-drum-utils/files/6016595/do_it.sh.txt)

**Comment by Improhardwarejam** [comment]
Would it be possible for person without any python knowledge(or any other codeing program) To change custom samples in future?

**Comment by mungewell** [comment]
@Improhardwarejam Yes, it should be fairly easy, the 'do_it.sh' is actually a shell script, and once I release the pre-built packages I will also convert this to a '.bat' file as well. All it does is use the 'sox' application to convert user's sound samples to the right format and then call the python code to build the sound pack.

I have trimmed the suggested samples down a bit and used one of the other (longer) Anthology sound packs as a template. It now build a new pack from the DS100 sounds without error....
```
Number of samples: 54
Sample 1-1: 5440 (8160 bytes, 0.170000 sec)
Sample 1-2: 3520 (5280 bytes, 0.110000 sec)
Sample 1-3: 3840 (5760 bytes, 0.120000 sec)
Sample 1-4: 3200 (4800 bytes, 0.100000 sec)
Sample 1-5: 1920 (2880 bytes, 0.060000 sec)
Sample 2-1: 13159 (19739 bytes, 0.411219 sec)
Sample 2-2: 13622 (20433 bytes, 0.425687 sec)
Sample 2-3: 12422 (18633 bytes, 0.388188 sec)
Sample 2-4: 9604 (14406 bytes, 0.300125 sec)
Sample 2-5: 6422 (9633 bytes, 0.200687 sec)
Sample 3-1: 541 (812 bytes, 0.016906 sec)
Sample 3-2: 1340 (2010 bytes, 0.041875 sec)
Sample 3-3: 3679 (5519 bytes, 0.114969 sec)
Sample 3-4: 318 (477 bytes, 0.009938 sec)
Sample 3-5: 12322 (18483 bytes, 0.385062 sec)
Sample 4-1: 2880 (4320 bytes, 0.090000 sec)
Sample 4-2: 3841 (5762 bytes, 0.120031 sec)
Sample 4-3: 4801 (7202 bytes, 0.150031 sec)
Sample 4-4: 8013 (12020 bytes, 0.250406 sec)
Sample 4-5: 4008 (6012 bytes, 0.125250 sec)
Sample 5-1: 11200 (16800 bytes, 0.350000 sec)
Sample 5-2: 13440 (20160 bytes, 0.420000 sec)
Sample 5-3: 8320 (12480 bytes, 0.260000 sec)
Sample 5-4: 4480 (6720 bytes, 0.140000 sec)
Sample 5-5: 8640 (12960 bytes, 0.270000 sec)
Sample 6-1: 35200 (52800 bytes, 1.100000 sec)
Sample 6-2: 22400 (33600 bytes, 0.700000 sec)
Sample 6-3: 26240 (39360 bytes, 0.820000 sec)
Sample 6-4: 30400 (45600 bytes, 0.950000 sec)
Sample 6-5: 14720 (22080 bytes, 0.460000 sec)
Sample 7-1: 8028 (12042 bytes, 0.250875 sec)
Sample 7-2: 6417 (9626 bytes, 0.200531 sec)
Sample 7-3: 9604 (14406 bytes, 0.300125 sec)
Sample 7-4: 32022 (48033 bytes, 1.000687 sec)
Sample 8-1: 16025 (24038 bytes, 0.500781 sec)
Sample 8-2: 12817 (19226 bytes, 0.400531 sec)
Sample 8-3: 16026 (24039 bytes, 0.500812 sec)
Sample 8-4: 12807 (19211 bytes, 0.400219 sec)
Sample 9-1: 4160 (6240 bytes, 0.130000 sec)
Sample 9-2: 4823 (7235 bytes, 0.150719 sec)
Sample 9-3: 4826 (7239 bytes, 0.150812 sec)
Sample 9-4: 6423 (9635 bytes, 0.200719 sec)
Sample 10-1: 5120 (7680 bytes, 0.160000 sec)
Sample 10-2: 3200 (4800 bytes, 0.100000 sec)
Sample 10-3: 2560 (3840 bytes, 0.080000 sec)
Sample 10-4: 5440 (8160 bytes, 0.170000 sec)
Sample 11-1: 4160 (6240 bytes, 0.130000 sec)
Sample 11-2: 7040 (10560 bytes, 0.220000 sec)
Sample 11-3: 7360 (11040 bytes, 0.230000 sec)
Sample 11-4: 5760 (8640 bytes, 0.180000 sec)
Sample 12-1: 19200 (28800 bytes, 0.600000 sec)
Sample 12-2: 12800 (19200 bytes, 0.400000 sec)
Sample 12-3: 12800 (19200 bytes, 0.400000 sec)
Sample 12-4: 9600 (14400 bytes, 0.300000 sec)
Total length: 778431 bytes
Total length: 16.217188 sec
```

I'll give it a quick test on the UNO and then upload :-)

**Comment by Improhardwarejam** [comment]
@mungewell Nice! Keen to hear hows it gonna work.
Still For me To do this i would need step by step guide -_-

**Comment by mungewell** [comment]
Success! Demo DFU is built, see:
https://github.com/mungewell/uno-drum-utils/releases/tag/v0.1.0

The basic flow is:
'--unpack' existing DFU (or just create a new/empty directory)
Copy in your own samples with the right name, sample rate, etc ('sox' is used in the script to convert the samples from DS1000 zip)
'--pack' this directory using existing DFU as a template and '--output' to new DFU file

Once the DFU is created it needs to be copied somewhere where IK's uploader EXE exists, for example:
`C:\Program Files\IK Multimedia\UNO Drum Anthology Libraries WIN\UNO Drum Factory Sound Content Installer 1.0.0 WIN`
and renamed to `Uno_Drum_lib.dfu`.

Run the application `UNO Drum Sound Content Installer.exe` and follow instructions. 

This will overwrite the official samples with those you have packed into your custom DFU.

**Comment by Improhardwarejam** [comment]
Yes!!! I managed To transfer the pack!! Thank you thousand times and if you are into making more custom packs, im in! Lets make Uno drum great again ;)

**Comment by Improhardwarejam** [comment]
You are the Best @Mungewell 😊
