### ISSUE TITLE
Maximum length for sample

### ISSUE THREAD

**Issue by mungewell** [mungewell/uno-drum-utils#7]
Implemented a 'pack' function to build a DFU from just the specified samples (ie not just replacing). This allows for longer samples to be added, but they do not play properly.

```
$ python3 decode_sound_packs.py -s long.dfu
Opening: long.dfu
Number of samples: 25
Sample 1-1: 5351 (8027 bytes, 0.167219 sec)
Sample 1-2: 9600 (14400 bytes, 0.300000 sec)
Sample 1-3: 144320 (216480 bytes, 4.510000 sec)
Sample 2-1: 8114 (12171 bytes, 0.253563 sec)
Sample 2-2: 14221 (21332 bytes, 0.444406 sec)
Sample 3-1: 541 (812 bytes, 0.016906 sec)
Sample 3-2: 1280 (1920 bytes, 0.040000 sec)
Sample 4-1: 4635 (6953 bytes, 0.144844 sec)
Sample 4-2: 4480 (6720 bytes, 0.140000 sec)
```

The long sample is cut short when played, and it's audio data is also played by following pads. It unpacks "correctly", so I suspect my understanding of the DFU format is a bit wrong.... it could be that the length (in samples) is not 'Int24ul' but instead 'Int16ul'

**Comment by mungewell** [comment]
With 16bit sample count, that would give maximum sample length of 2sec.

**Comment by mungewell** [comment]
```
$ python3 decode_sound_packs.py -s long.dfuOpening: long.dfu
Number of samples: 25
Sample 1-1: 5351 (8027 bytes, 0.167219 sec)
Sample 1-2: 9600 (14400 bytes, 0.300000 sec)
Sample 1-3: 65535 (98303 bytes, 2.047969 sec)
Sample 2-1: 8114 (12171 bytes, 0.253563 sec)
Sample 2-2: 14221 (21332 bytes, 0.444406 sec)
Sample 3-1: 541 (812 bytes, 0.016906 sec)
```

**Comment by mmelon** [comment]
Hi. I am not very good with github but just came to say this project is brilliant. I have an unodrum and can code a bit. Mainly JS. I really don't understand why IK are keeping the sample implementation under wraps. Makes no sense. Anyway if you think I can do anything to help, let me know.

**Comment by mungewell** [comment]
I made good progress and hope to make a release (with pre-built binaries) soon. This will allow Windows user to make packs without the need to install Python and associated requirements.

**Comment by mungewell** [comment]
Over a year later and we have a release (with pre-built binaries for Windows) which will let you construct your own sample libraries (".dfu" files).

Each individual sample is limited to 65536 sample @ 32KHz (~2s), but also note that they can be tuned up/down to 2x/0.5x speed.
